name: calculator website deployment on docker  using github actions
on: workflow_dispatch
  # release:
  #   types: [published]

jobs:
  push_to_registry:
    name: build and push image to docker hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: checkout the repo code
        uses:  actions/checkout@v4

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            rakesh9711/calculator:${{ github.ref_name }}
            rakesh9711/calculator:latest
          outputs: type=docker,dest=${{ runner.temp }}/myimage.tar

      - name: upload docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-image
          path: ${{ runner.temp }}/myimage.tar